### ISSUE TITLE
TypeError: 'NoneType' object is not iterable with key press of alt + shift + (up or down) 

### ISSUE THREAD

**Issue by AnthonyWC** [DougTy/sublime-compare-side-by-side#18]
See these errors in console (after uninstall & reisntall) when pressing alt + shift + (up or down)

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "sbs_compare in /home/antho/.config/sublime-text-3/Installed Packages/Compare Side-By-Side.sublime-package", line 643, in run
  File "sbs_compare in /home/antho/.config/sublime-text-3/Installed Packages/Compare Side-By-Side.sublime-package", line 615, in sbs_scroll_to
TypeError: 'NoneType' object is not iterable
```

**Comment by DougTy** [comment]
Thanks for the heads up! Should be fixed now.
