### ISSUE TITLE
hotkeys do not work

### ISSUE THREAD

**Issue by snowyxx** [DougTy/sublime-compare-side-by-side#32]
next/previous hot keys does not work. When press alt+shift+down or alt+shift+up, nothing happened.

- sublime text 2
- macOS

console output:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sbs_compare.py", line 710, in run
  File "./sbs_compare.py", line 682, in sbs_scroll_to
IndexError: Index out of range
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sbs_compare.py", line 710, in run
  File "./sbs_compare.py", line 682, in sbs_scroll_to
IndexError: Index out of range
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sbs_compare.py", line 706, in run
  File "./sbs_compare.py", line 693, in sbs_scroll_to
Boost.Python.ArgumentError: Python argument types in
    Region.__init__(Region, float)
did not match C++ signature:
    __init__(_object*, long long)
    __init__(_object*, long long, long long, double)
    __init__(_object*, long long, long long)

PS: I tried to config different hotkeys, same issue come.

**Comment by DougTy** [comment]
I am unable to reproduce this with Sublime Text 2.0.2 build 2221 and Arch Linux, pushing alt+shift+down correctly jumps to the next change with no error.

My intuition is that something is wrong with your install of Sublime, as that's not a typical looking error for a plugin, and instead looks like something is very wrong internally. Are you on the latest version of ST2? Perhaps a reinstall may fix this.

**Comment by DougTy** [comment]
As it's been a while with no response and I cannot reproduce the issue, I will be closing this thread. Please let me know if the issue persists & if you have any further info that could help troubleshoot.
